#!/usr/bin/env bash
################################################################################
#: Title       : Iptable rules for web browser 
#: Date        : 2017-Dec-12
#: Author      : Anthony Tilelli
#: Version     : 1
#: Description : #Create iptable rules via command line
#strict mode (http://redsymbol.net/articles/unofficial-bash-strict-mode/)
set -euo pipefail
#IFS=$'\n\t'
################################################################################

#Allow local host
iptables -A INPUT -i lo -j ACCEPT
iptables -A OUTPUT -o lo -j ACCEPT

# New connections should start with syn
iptables -A INPUT -p tcp ! --syn -m state --state NEW -j DROP

# Malformed packets
iptables -A INPUT -p tcp --tcp-flags ALL NONE -j DROP # null
iptables -A INPUT -p tcp --tcp-flags ALL ALL -j DROP # XMAS packets

# Allow existing connections and new 22 80 443 over tcp connections
iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A INPUT -p tcp --dport 22 -m state --state NEW -s 0.0.0.0/0 -j ACCEPT
iptables -A INPUT -p tcp --dport 80 -m state --state NEW -s 0.0.0.0/0 -j ACCEPT
iptables -A INPUT -p tcp --dport 443 -m state --state NEW -s 0.0.0.0/0 -j ACCEPT

# Allow existing connections outbound and DNS PACKETS
iptables -I OUTPUT 1 -m state --state RELATED,ESTABLISHED -j ACCEPT
#iptables -A OUTPUT -p udp --dport 53 -m state --state NEW -j ACCEPT #  allow dns on server

iptables -P FORWARD DROP
iptables -P INPUT DROP
iptables -P OUTPUT
