---
- hosts: webservers
  become: true
  tasks:
  - assert: { that: "ansible_os_family == 'Debian'" }
  #tested using Ubuntu

  - name: "Preventing Permit root ssh login"
    lineinfile:
      path: /etc/ssh/sshd_config
      state: present
      regexp: '^PermitRootLogin'
      line: "PermitRootLogin no"
    when: ansible_user != "root"
    notify:
      - restart sshd service

  #Install Packages
  - name: Install needed packages
    block:
    - apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - 'apache2'
        - 'python-pip'
    - pip:
        name: pyOpenSSL

  #Set up firewall
  - name: synchronizing firewall rules (ip4)
    template:
      src: templates/ip4tables_rules_save
      dest: /etc/ip4tables.up.rules
      owner: root
      group: root
      mode: '0644'
      backup: yes
    notify:
      - apply firewall rules
  - name: synchronizing firewall rules (ip6)
    template:
      src: templates/ip6tables_rules_save
      dest: /etc/ip6tables.up.rules
      owner: root
      group: root
      mode: '0644'
      backup: yes
    notify:
      - apply firewall rules

  - name: Making firewall persistent
    template:
      src: templates/iptables_network_script
      dest: /etc/network/if-pre-up.d/iptables
      owner: root
      group: root
      mode: '0755'
      backup: no
    notify:
      - apply firewall rules

    #Creating selfsigned certificate
  - name: Make certificate folder
    file:
      path:  /etc/ssl/webserver
      state: directory
      mode: '0750'
      owner: root
      group: www-data
  - name: Create private key
    openssl_privatekey:
      path: /etc/ssl/webserver/example.com.pem
      state: present
  - name: Create CSR
    openssl_csr:
      path: /etc/ssl/webserver/example.com.csr
      privatekey_path: /etc/ssl/webserver/example.com.pem
      common_name: www.example.com
      country_name: US
      organization_name: example.com
      email_address: user@example.com
  - name: Create CA  (self Signed)
    openssl_certificate:
      path: /etc/ssl/webserver/example.com.crt
      privatekey_path: /etc/ssl/webserver/example.com.pem
      csr_path: /etc/ssl/webserver/example.com.csr
      provider: selfsigned
  - name: Make KEY apache readable
    file:
      path:  /etc/ssl/webserver/example.com.pem
      state: file
      mode: '0740'
      owner: root
      group: www-data
  - name: Make Cert apache readable
    file:
      path:  /etc/ssl/webserver/example.com.crt
      state: file
      mode: '0740'
      owner: root
      group: www-data

#configure Apache
  - name: remove 000-default
    file:
      path: /etc/apache2/sites-enabled/000-default.conf
      state: absent
    notify:
     - restart apache2 service
  - name: Enable ssl module
    apache2_module:
      state: present
      name: ssl
    notify:
     - restart apache2 service
  - name: Setting up VirtualHost conf
    template:
      src: templates/virtualhost_conf
      dest: /etc/apache2/sites-available/vh.conf
      owner: root
      group: root
      mode: '0744'
      backup: no
    notify:
     - restart apache2 service
  - file:
      src: /etc/apache2/sites-available/vh.conf
      dest: /etc/apache2/sites-enabled//vh.conf
      owner: root
      group: root
      state: link
    notify:
     - restart apache2 service
  - name: setting website content
    template:
      src: templates/webpage
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: '0744'
      backup: no
  - meta: flush_handlers

  - name: Checking webpage
    block:
      - uri:
          url: https://104.131.134.28
          validate_certs: no
    rescue:
       - debug: msg='Website seem to not be working, attempting recovery'
       - service:
           name: apache2
           state: restarted
       - shell: 'iptables-restore < /etc/ip4tables.up.rules'
       - shell: 'ip6tables-restore < /etc/ip4tables.up.rules'
       - debug: msg="Trying again"
       - uri:
          url: https://104.131.134.28
          validate_certs: no

  handlers:
    - name: restart apache2 service
      service:
        name: apache2
        state: restarted
    - name: restart sshd service
      service:
        name: ssh
        state: restarted
    - name: apply firewall rules
      shell: 'iptables-restore < /etc/ip4tables.up.rules'
      shell: 'ip6tables-restore < /etc/ip6tables.up.rules'
