---
# handlers file for webserver-firewall
- name: store firewall rules
  shell: iptables-save >  /etc/ip4tables.up.rules

- name: store firewall rules 2
  listen: store firewall rules
  shell: ip6tables-save > /etc/ip6tables.up.rules
  
